### ISSUE TITLE
No NitroHax.cia file

### ISSUE THREAD

**Issue by sacredtyras** [ahezard/NitroHax3DS#10]
There isn't a nitrohax cia file in the download, and I cant find the download for it online. Ive never used make_cia.exe before and Im not sure how to get the file. Please help.

**Comment by vaaino** [comment]
The releases page: https://github.com/ahezard/NitroHax3DS/releases

**Comment by sacredtyras** [comment]
It says this is the dsi version?
I apologize, I see the file!
