### ISSUE TITLE
When using wiimmfi mkds ar code, mkds freezes upon connecting to wiimmfi wfc

### ISSUE THREAD

**Issue by MDHEXT** [ahezard/NitroHax3DS#11]
When I use the Mario kart DS action replay wiimmfi patch code, Mario kart DS freezes when connecting to the wfc alternative.

**Comment by ApacheThunder** [comment]
You no longer need to patch DS games for using alternate WFC servers. Just change DNS to the new servers and play the game without modification!

https://gbatemp.net/threads/nds-constraint-taking-advantage-of-a-flaw-in-the-nintendo-ds-i-ssl-library.522011/

You just need to use DNS replacement servers that take advantage of that. ;)

**Comment by MDHEXT** [comment]
Can you send me the DNS settings??? It has to be for wiimmfi tho.

**Comment by Valkristh** [comment]
164.132.44.106
8.8.8.8
That's it

**Comment by MDHEXT** [comment]
Hey thanks man!!!! I'll see if I can close the issue now.

**Comment by MDHEXT** [comment]
Unfortunately, I can't close the issue, but please feel free to do so as my issue is now solved.

**Comment by ApacheThunder** [comment]
This issue closed per user requiest.
