### ISSUE TITLE
Rom loading Support?

### ISSUE THREAD

**Issue by theclashingfritz** [ahezard/NitroHax3DS#2]
The 3DS hacking scene has come a long way with things like TWL Loader and such. It'd be cool if either Rom Support is added or this projects functionality is ported to TWL Loader.

**Comment by ApacheThunder** [comment]
NitroHax3DS is geared towards bringing cheat support to legit carts. At this point in time there are no plans to make it a rom loader. If you want cheat codes for roms running off SD you should mention this on the nds-bootstrap github instead.
