### ISSUE TITLE
Any way of building  this in a 3dsx?

### ISSUE THREAD

**Issue by dvdcd** [ahezard/NitroHax3DS#6]
With the big ban waves going around, a bunch of us don't want to use cia apps. it'd be awesome if this  had a 3dsx copy. i don't know if you can do this, as its dsiware.

**Comment by ApacheThunder** [comment]
3dsx files run in CTR mode and can't interact with TWL_FIRM titles which run in legacy mode. (aka TWL or NTR modes respectively)

Issue closed due to being impossible on current hardware.

**Comment by dvdcd** [comment]
Ok, thanks anyway!

**Comment by ApacheThunder** [comment]
Yeah sorry. The only way to do it via 3dsx is to have that 3dsx app launch a modified DSiWare title and that would still show up in the logs and what not so defeats the purpose of going 3DSX only which isn't possible here. :(
