### ISSUE TITLE
Golden Sun: Dark Dawn unsupported

### ISSUE THREAD

**Issue by RainbowHackerHorse** [ahezard/NitroHax3DS#7]
Golden Sun: Dark Dawn does not launch with release 0.99
When launching it, a white screen appears and stays until you exit to the home screen.

I am happy to test development builds to add support for this game.

**Comment by ApacheThunder** [comment]
Is this a TWL enhanced game or a newer game using TWL cart? (check the game code on the cart label. If it starts with NTR then it should be an older NTR game. But if it starts with TWL, it uses a DSi Extended header and uses TWL cart. Currently the cart loading code for NitroHax (and NTR Launcher which is based on NitroHax) can't handle any TWL carts at all right now.

**Comment by RainbowHackerHorse** [comment]
@ApacheThunder it's an NTR game: NTR-B05E-USA
It's a fairly old game at this point, about 8 years since launch.
https://en.wikipedia.org/wiki/Golden_Sun:_Dark_Dawn
Thanks for responding :)

**Comment by ApacheThunder** [comment]
Oh interesting. Hmm perhaps look at placing an issue here instead:

https://github.com/chishm/nitrohax

This is the original build of NItroHax made by Chrishm himself. Anything thing he adds would be added to this fork of NitroHax anyways and right now we aren't actively working on NitroHax. It may be pushed faster if you make this issue known to the original creator instead. If he implements a fix we can add it faster. ;)

**Comment by RainbowHackerHorse** [comment]
Thanks for the FYI.
Opened at https://github.com/chishm/nitrohax/issues/3

**Comment by RainbowHackerHorse** [comment]
@ApacheThunder 
Fix has been upstreamed as of https://github.com/chishm/nitrohax/commit/1dacaf200946ba478ee2228d046e9a29d102d7d3
Happy to test the next build on my 3DS :)

**Comment by RainbowHackerHorse** [comment]
@ApacheThunder  Happy to build and test! Thanks for merging the change in! Any documentation on the build process I can look at?
I've not done much (read: anything except using) in the 3DS Homebrew scene, bit of a fish out of water when it comes to this platform :)

**Comment by RainbowHackerHorse** [comment]
Scratch that last one: I assume this is what I should be looking at, yeah?
https://3dbrew.org/wiki/Setting_up_Development_Environment
(Shame, there's no FreeBSD port for DevkitARM yet. Something for me to do this weekend!)

**Comment by ApacheThunder** [comment]
Well I compiled and made a CIA of it. But the source I have has some changes compared to the last commit. I don't remember why.


https://mega.nz/#!WPoQiCaB!myQqYqMgaWSWcJXr-_oYTFPxEJBmunVIWg344wX1Dvs


CIA of the updated build. If it doesn't work correctly I'll build the one that is inline with what the github repo has.

Can't test this on 3DS, but that should do it for you. Let me know if there are any issues.

**Comment by ApacheThunder** [comment]
Ok turns out there wasn't a lot of INI file stuff in NitroHax as there was in NTR_Launcher. Already got a HiyaCFW build working. (Basically the file I just sent you). It works on DSi. Should work fine on 3DS as well.

**Comment by RainbowHackerHorse** [comment]
Thank you!
I still really should look into porting the toolchain over and helping get binary builds up for FreeBSD, but now I can test this build over my lunch break :)
I owe you a drink Sir Thunder; lemme know if you're ever in SF. (I'm serious, by the way. Whisky on me. The cost of it i mean...not literally on...er...YOU GET WHAT I MEAN.)

**Comment by ApacheThunder** [comment]
lol well I live no where near that. Plus I don't drink alcoholic drinks. Tried that when I turned 21...Decided that wasn't for me. :P
